name: Template Test PR

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      project_repo:
        type: string
        required: true
      pr_body:
        type: string
    secrets:
      access_token:
        required: true

# all access is via the provided `access_token`
permissions: {}

env:
  BRANCH_NAME: ${{ inputs.branch_name }}

jobs:
  create-or-update-pr:
    name: Create or update PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          path: project-repo
          repository: ${{ inputs.project_repo }}
          token: ${{ secrets.access_token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install nava-platform CLI
        run: pipx install --python "$(which python)" git+https://github.com/navapbc/platform-cli

      - name: Configure git
        working-directory: project-repo
        run: |
          git config user.name nava-platform-bot
          git config user.email platform-admins@navapbc.com

      - name: Set up PR branch
        working-directory: project-repo
        run: |
          git checkout -b "${BRANCH_NAME}"

      - name: Update infra template
        working-directory: project-repo
        run: nava-platform infra update --template-uri ${{ github.server_url }}/${{ github.repository }} --version "${BRANCH_NAME}" .

      - name: Push changes to project repo
        working-directory: project-repo
        run: git push --force --set-upstream origin HEAD

      - name: Check for existing PR
        id: check-pr
        working-directory: project-repo
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
        run: |
          PR_URL="$(gh pr list --head "${BRANCH_NAME}" --state open --json url --jq .[].url)"
          if [[ -n "${PR_URL}" ]]; then
            echo "PR already exists -> ${PR_URL}"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "PR does not exist (or is not open)"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Open Pull Request
        if: ${{ steps.check-pr.outputs.exists != 'true' }}
        working-directory: project-repo
        env:
          GITHUB_TOKEN: ${{ secrets.access_token }}
          PR_BODY: ${{ inputs.pr_body }}
        run: |
          if [[ -n "${PR_BODY}" ]]; then
            : # we're good
          elif [[ -n "${{ github.event.pull_request.html_url }}" ]]; then
            PR_BODY="${{ github.event.pull_request.html_url }}"
          else
            PR_BODY="${{ github.server_url }}/${{ github.repository }}/tree/${BRANCH_NAME}"
          fi

          gh pr create \
            --body "${PR_BODY}" \
            --title "Test Template PR: ${BRANCH_NAME}"
